### ISSUE TITLE
Error "Cannot GET /" upon start

### ISSUE THREAD

**Issue by rene-schoene** [geodes-sms/gentleman#13]
When starting using `npm start`, the landing page of http://localhost:8080/ shows only a plain error

```
Cannot GET /
```

## My environment

- `npm --version` = `6.14.6`
- Tested browser: Brave, Firefox
- Removed ` --open 'chrome'` in `package.json` at `scripts.start` to avoid starting Chrome by default (which I have not installed)

(Disclaimer: I have very little experience with JavaScript)

If more information and/or logs are needed, I can happily provide them given some instructions.

**Comment by henrikeU** [comment]
solved in 0.2.0
